name = "CTD_AM"
uuid = "6b0a8e3f-e318-4410-9520-cf40d40c3d3e"
authors = ["Satyajit Mojumder <smojumder018@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
